#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the route that will allow LexikJWT to intercept the request
api_login:
  path: /api/login_check
  methods: ['POST']

app_logout:
  path: /logout
  methods: ['GET']